### ISSUE TITLE
Dropping maintainer info from Funtoo

### ISSUE THREAD

**Issue by juippis** [repology/repology#925]
Hey, 

I'm kindly approaching due to Funtoo "wrongly" reporting the package status for maintainers. I saw a recent commit about disabling maintainers from certain repos, 
5ef34e63ab04777b7503447335074f6a5f6a58ee
and believe Funtoo should be added to that list. Gentoo developers have no control over what gets pulled to Funtoo and when, so ever since Funtoo became a release-based distribution, it falsifys up-to-date status for Gentoo developers in Repology. Also as @palica said, https://github.com/repology/repology/issues/824#issuecomment-481530759 Funtoo doesn't have a maintainer concept - they just copy metadata from Gentoo. 

So I'm kindly asking to drop maintainer info from Funtoo in Repology as I see it's possible to do (I can make a PR about it), 
or alternatively @danielrobbins to update all package maintainer info into "@funtoo.org" (might require a bit more work).

I invite discussion about this subject, I know many Gentoo developers have shown frustration about this.

**Comment by danielrobbins** [comment]
I do not use repology so I don't know what the "fuss" is about, but it seems like having Funtoo make changes to metadata for the sake of repology is a bit like the tail wagging the dog.

As far as this issue -- all I can say is that I am totally unware of this until it was brought to my attention by @juippis in #funtoo on freenode just now. A comment from @palica, a Funtoo user, doesn't indicate that this issue has ever been explained to the Funtoo project. So it is completely off our radar. Therefore, any mitigation on repology's end seems premature.

I would appreciate anyone concerned about this in regards to funtoo to OPEN A BUG on the funtoo bug tracker so the exact problem can be described in detail and a solution proposed.

**Comment by danielrobbins** [comment]
Regarding the yet-to-be discussed technical issue, Funtoo takes a snapshot of Gentoo at a particular point in time. Most of the ebuilds in Funtoo come from that snapshot, and are maintained by those maintainers that metadata.xml says they are. So I don't see what the issue is here. Please describe the actual problem in detail so I can understand it.

"Gentoo developers have shown frustration about this" -- only evidence I have seen is mgorny making a passing nasty comment about it (this was mixed in with him spreading slander about me in the #gentoo-trustees channel) and likely rounding up a flock of enraged Gentoo developers focused on this issue. How is this actually negatively impacting Gentoo? If developers are upset, they have not made any constructive effort to resolve the issue. I imagine that they understand the proper way to engage with another open source project? So I am guessing that these "many" developers can't be all that hot and bothered about this issue.

**Comment by lovesegfault** [comment]
@danielrobbins My understanding of the issue is that many people, myself included, use Repology to track the packages they maintain and to see that they are all up-to-date, here's [my page](https://repology.org/projects/?maintainer=bernardo%40standard.ai) for example. When things are good, you'll see all your packages as green or green/yellow, and that feel pretty good, it's a visual signifier of a job well done, and also makes it easy for the maintainer to quickly see if any packages are out of date (just do a visual scan for a red square.)

Now, I think the complain is that when Funtoo performs its snapshot, the Gentoo maintainers show up as Funtoo maintainers as well on Repology, which soon enough means all their packages are out of date, and now it becomes difficult to visualize what is up to date or not since there will be red-marked versions everywhere.

I, personally, have not had this issue, but I completely understand the frustration of those who have.

**Comment by mgorny** [comment]
No, the issue is that packages **we no longer maintain** show as maintained by us because Funtoo supplies obsolete metadata.xml files. Even filtering to Gentoo repository only does not help with that.

**Comment by danielrobbins** [comment]
@mgorny OK. I get it now. But you are stating something that is false:

"No, the issue is that packages we no longer maintain show as maintained by us because Funtoo supplies obsolete metadata.xml files."

Nope. That's you're little spin on the problem, with your own little incorrect blame assignment, which is a personal problem of yours you should probably work on. 

The real "because" is: Funtoo takes a snapshot of the Gentoo tree. Repology is showing that snapshotted Funtoo ebuilds are maintained by Gentoo is because *repology is not properly understanding that this information is coming from a snapshot that is part of another distribution and does not reflect the state of ebuilds in Gentoo.* That is the actual, legitimate, technical "because."

For importing official maintainership information for ebuilds in Funtoo, repology should understand that Funtoo's ebuilds are not an authoritative source of information for ebuilds in the Gentoo project. They are two separate projects. The concept of one distribution being derived from another isn't exactly novel and is something that repology needs to be able to understand because it happens ALL THE TIME and ALL OVER THE PLACE in Linux distribution-land.

Funtoo, at this time, does not use maintainership metadata. This is simply part of our snapshot from Gentoo. It would be nice to be able to use it in the future. So, really, repology could perform the following steps when dealing with Funtoo metadata to solve this problem.

Ignore all maintainer type="project" data. This is used to specify Gentoo projects and the Funtoo data is not "live" and can be stale. If we start using this info, I can figure out some way to specify a non-Gentoo project in the XML.

Ignore all maintainer type="person" data where the email ends with @gentoo.org. This would indicate the ebuild is maintained by Gentoo, and thus any maintainership metadata is not authoritative.

Really, the metadata from Funtoo should not trigger updates to the Gentoo metadata, at all. They are different distributions so I can't really figure out why this is an issue in the first place. But I can speak authoritatively on how Funtoo's metadata should be interpreted. And that is how it should be interpreted. So, at least for now, as @juippis was suggesting, mostly ignored.

**Comment by mgorny** [comment]
Let me reply to a few points raised here.

> I would appreciate anyone concerned about this in regards to funtoo to OPEN A BUG on the funtoo bug tracker so the exact problem can be described in detail and a solution proposed.

I wanted to but as you know, you've closed the bug tracker to privacy-aware people who do not wish to give away their phone number to third-party services.

> Most of the ebuilds in Funtoo come from that snapshot, and are maintained by those maintainers that metadata.xml says they are.

No. They were maintained by those people **before** Funtoo copied them. The majority of Gentoo developers won't be spending their effort maintaining obsolete versions of their packages in a fork of their distribution. Claiming that they maintain them is plain lying.

> The concept of one distribution being derived from another isn't exactly novel and is something that repology needs to be able to understand because it happens ALL THE TIME and ALL OVER THE PLACE in Linux distribution-land.

Except that other distributions (see e.g. Ubuntu) have enough reason not to copy maintainer information from parent project.

> Ignore all maintainer type="person" data where the email ends with @gentoo.org. This would indicate the ebuild is maintained by Gentoo, and thus any maintainership metadata is not authoritative.

Right now, there's 317 non-@gentoo.org maintainers in Gentoo, so that won't work at all. Also, I'd really appreciate if Gentoo forks didn't try to add custom meaning to metadata from Gentoo.

**Comment by danielrobbins** [comment]
@mgorny 

The reality is that even stale metadata can be useful as it indicates who actually developed the ebuild we are using at the time the snapshot was taken. If I "update" the metadata, it could be "stale" in that maintainers could have changed. If I remove it, then I don't have it. I personally use this information, so I need it to be in our tree.

It is disturbing to see you attempt to assign some kind of immoral intent to it. 

From what I understand, the Portage tree is released under the GPL version 2. I seem to recall choosing this license when I created the Portage tree. I can do whatever I want with it under the terms of the GPL. There is no clause in the GPL that dictates that I update the maintainer information to meet your personal requirements. Maybe you should re-read it? (You *have* read it, right?)

Anyway, this is a repology problem, and I explained how it needs to be fixed. Repology should understand that Funtoo is based on a snapshot of Gentoo and that metadata is not authoritative. I am still not sure exactly how repology handles that internally and why it is grabbing Funtoo maintainership information in the first place, as I am not a repology developer, but I think that there's enough information in this bug for a repology developer to understand the problem and fix it.

There are other possible solutions to this problem, such as looking at how the metadata.xml model translates into snapshotted distributions, and some good ideas to make this work better in the future, but I don't think this is the forum for discussing those.

**Comment by danielrobbins** [comment]
Thanks @palica for the fix for this. The new YAML excludes metadata.xml from the Funtoo repo clones so it should not get any maintainer information from Funtoo, which should resolve this issue, as long as the repology parser can still do basic processing without metadata.xml (I would guess it probably can.)

@mgorny remember to read the GPLv2  when you have a chance.

**Comment by danielrobbins** [comment]
Just checked the repology gentoo parser -- it will work correctly without metadata.xml :+1:

**Comment by a17r** [comment]
Thanks for addressing this.

**Comment by palica** [comment]
no problem :)

**Comment by AMDmi3** [comment]
The patch does not fix the problem. Ignoring all metadata also drops homepage information which is crucial for splitting projects with conflicting names, I cannot accept that.

> I saw a recent commit about disabling maintainers from certain repos

It's not related; it tweaks the way _default maintainer_ is assigned - it affects cases where maintainer is not defined in the repository or cannot be parsed, not the cases where maintainer is defined.

Regarding the problem, my position is as follows: Repology conveys the state of upstream repos, as close to original as possible. So if there's inaccurate information (I'm not stating this though, it most likely isn't) in Funtoo which bothers Gentoo maintainers (in other ways than just Repology), it should be fixed in Funtoo. Ignoring it in Repology would only mask the problem, as any another client would again take inaccurate maintainer information from the metadata, and teaching all existing (and future) clients to ignore the information from Funtoo is what I'd call "the tail wagging the dog".

This kind of situation is not specific to Gentoo. DPorts derived from FreeBSD ports are exactly the same, and in fact whole Debian-derived family is similar too. Going deeper, the whole RPM repository family is also somewhat similar, as there's package information exchange between more and less related repositories, up and down the timeline. Even older versions of the same repository is affected by this problem (very much in fact - if maintainer steps down from his position, no repository known to me has the policy to update metadata of older versions).

I'm mentioning these to demonstrate that in general the relationships between repositories may be quite complex, and (not always correct) inheritance of maintainer information cannot be dealt with by just disabling maintainers in some repositories. Consider [this](https://repology.org/maintainer/mpitt%40debian.org) example - this is top maintainer known to repology by number of repositories he's mentioned in - I'm pretty sure that in fact he's active in Debian and may not even know some of these distributions. Which does not justify ignoring maintainers from these at all.

To cope with that, Repology ties (or at least tries to) all maintainer activity to repositories. For instance, though it may look overcomplicated on first glance, maintainer feeds are tied to repositories. Project list for a maintainer is also supposed to be also filtered by repository.

There's, however, problem #655 which breaks this for metapackage search, as repository + maintainer condition is handled as `repository OR maintainer` instead of `repository AND maintainer`. This issue does not specify what is implied by

> it falsifys up-to-date status for Gentoo developers in Repology

but I expect it to be the same problem. If it is, please kindly close this in favor of #655, otherwise please elaborate in which way Gentoo maintainers are affected by Funtoo in Replogy.

**Comment by danielrobbins** [comment]
@juippis can you review #655 and see if this appears to be the problem you are experiencing? If so, it appears this issue can be closed.

**Comment by juippis** [comment]
> 
> but I expect it to be the same problem. If it is, please kindly close this in favor of #655, otherwise please elaborate in which way Gentoo maintainers are affected by Funtoo in Replogy.

Apart from that I'll give out an example from my own workflow: 
Gentoo developers can help non-developer users to maintain their packages in Gentoo by committing on behalf of the users. The user gets put into the metadata, so they get maintain right for the package. 

If I had such a user, I'd like to keep track that they are active and keep the package in good shape (up-to-date etc). So I'd user repology to check how they're doing with their packages: 
(I can give real-life examples with private message, don't want anyone publically be dragged-in to this: )
So I'd go to https://repology.org/maintainers/?search=maintainer%40e.mail which would return something like 25 % - 60 % and that, at first sight, doesn't make me happy. But upon closer inspection, all their packages in Gentoo are up-to-date while outdated in Funtoo, which drags the percentage down I guess. 

https://repology.org/maintainers/?search=mozilla%40gentoo.org 
https://repology.org/maintainers/?search=llvm%40gentoo.org

check these for example. Gentoo has the latest versions, but this page shows 10 % up-to-date and requires manual work to determine the real situation, due to Funtoo. 

So using repology to determine maintainer / project activity is impossible as it requires manual check. And it all boils down to the maintainers having no power over what Funtoo does.

**Comment by AMDmi3** [comment]
Got it. This is in fact another case of incorrect (by my current idea of how Repology should behave; last time I've considered this it was more of "undecided") Repology behavior. There's an issue for it too: #539.

**Comment by AMDmi3** [comment]
Both issues should be solved now.

**Comment by juippis** [comment]
Thank you, I'm happy with the end result. Regarding your post here, 
https://github.com/repology/repology/issues/539#issuecomment-537507644
I think you already suggested it, but something like `search by maintainer && repo` could work sufficiently as well, if this most-active-repo method is troublesome for others.
